spring:
  application:
    name: Code_Review

server:
  port: 8080


langchain4j:
  open-ai:
    chat-model:
      api-key: ${DASHSCOPE_API_KEY:}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen-plus
      temperature: 0.7

classifier:
  async:
    concurrency: 5
  dirty:
    output-file: src/main/resources/static/task1_dirty_records.json
